### ISSUE TITLE
Highlighter treats "close" as a Go keyword whereas it is not

### ISSUE THREAD

**Issue by soygul** [atom/language-go#33]
Pretty self explanatory:

![image](https://cloud.githubusercontent.com/assets/617171/6542538/35bd1920-c4fb-11e4-866f-ce0899606a6f.png)

**Comment by thomasjo** [comment]
It seems like a built-in function to me: http://golang.org/pkg/builtin/#close

**Comment by soygul** [comment]
Oh totally forgot about that! I was fooled by the fact that you can create a variable named `close` and it is perfectly ok!

Closing this, as expecting the syntax highlighter to differentiate between a built-in function vs a variable with the name of a built in function is asking a bit too much!

**Comment by joefitzgerald** [comment]
I don't think it *is* asking too much to expect that to be differentiated. In one, there is no `(` as a suffix; in the other there is a `(`. Grammars are driven by regular expressions, and this distinction can be made.

**Comment by soygul** [comment]
Well I didn't inspect the code and I don't know how advanced it is but below is also another consideration if then:

```go
var (
  fn = func() { close(...) }
)
```

**Comment by joefitzgerald** [comment]
I would suggest reopening this issue.

**Comment by soygul** [comment]
Ok re-opening this and leaving it up to the project owners to decide.

**Comment by bassu** [comment]
This should be fixed by my latest commit in pull request #34, if it is merged.
It also marks these builtin functions' args as data types (just like what Emacs does)!

![solarized-dark-bold-go-builtinfuncs](https://cloud.githubusercontent.com/assets/977697/6659510/fd82f3ae-cba8-11e4-8e4b-b8408f1d750d.jpg)

**Comment by svanharmelen** [comment]
Yup... Looks as solved to me as well...

**Comment by soygul** [comment]
Didn't solve my specific case (see below) but still a good improvement.

![image](https://cloud.githubusercontent.com/assets/617171/7044066/c63231ea-ddef-11e4-8895-e511c6a7cf86.png)

**Comment by svanharmelen** [comment]
Check... Personally I do wonder if this is actually something that you would want. Syntactically your right, but if it will improve readability...?

Next to that it's of course a better practice to ***not*** make shadow variables over built-in names/types/functions

**Comment by soygul** [comment]
Ok gave this a second thought and a fix for this would actually *decrease* the readability. Otherwise it would be necessary to use a 3rd color to indicate shadowed variables to be spot on with what's going on.

Leaving it up to maintainers to close this as they like. I would consider this solved now.

**Comment by svanharmelen** [comment]
This is fixed in PR #58 and released in v0.36.0.
