### ISSUE TITLE
Comments inside var block are not hightlighted properly

### ISSUE THREAD

**Issue by bogdanovich** [atom/language-go#72]
<img width="681" alt="screen shot 2015-11-28 at 1 16 09 pm" src="https://cloud.githubusercontent.com/assets/5257258/11453940/5e5f77da-95d2-11e5-9ee1-cd5227b9a44e.png">

**Comment by svanharmelen** [comment]
This is already fixed in the latest version. You can install it by running 'apm install language-go' or wait until the next minor release of Atom (which includes the latest version).

**Comment by bogdanovich** [comment]
I just updated version to 0.40.0 and this bug is still there

**Comment by bogdanovich** [comment]
Thanks, i got this working by updating the package
